first commit

diff --git a/world/modulos/conexao b/world/modulos/conexao
--- a/world/modulos/conexao
+++ b/world/modulos/conexao
@@ -464,7 +464,7 @@ SCOLOR='\033[0m'
         fun_v2rayins() {
 			clear
 	        v2rayinst(){
-	            source <(curl -sL https://raw.githubusercontent.com/WorldSsh/prueba/main/world/modulos/v2ray)
+	            source <(curl -sL https://raw.githubusercontent.com/Niltonjuniornzx/nzx/main/world/modulos/v2ray)
                     sleep 6
 	        }
 	        if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
@@ -489,7 +489,7 @@ SCOLOR='\033[0m'
 	                conexao
 	            }
 	            v2rayinst
-       fi
+            fi
         }
     	fun_chisel() {
 		clear
@@ -769,7 +769,7 @@ SCOLOR='\033[0m'
 					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
 					#rm key.pem cert.pem >/dev/null 2>&1
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
-					cd /etc/stunnel && wget https://raw.githubusercontent.com/WorldSsh/prueba/main/world/instalador/stunnel.pem && cd $HOME
+					cd /etc/stunnel && wget https://raw.githubusercontent.com/Niltonjuniornzx/nzx/main/world/instalador/stunnel.pem && cd $HOME
 				}
 				fun_bar 'ssl_certif'
 				echo -e "\n\033[1;32mINICIANDO O SSL TUNNEL !\033[0m"
@@ -1474,12 +1474,15 @@ exit 0' >$RCLOCAL
 			sks='\033[1;31mOFF'
 		}
 		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m◉" || var_sks1="\033[1;31m○"
+		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m◉" || var_sks2="\033[1;31m○"
 		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m◉" || sksop="\033[1;31m○"
 		echo ""
 		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSOCKS DIRECT $var_sks1 \033[0m"
+		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET $var_sks2 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mSOCKS OPENVPN $sksop \033[0m"
 		echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m"
 		echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS SOCKS SSH\033[0m"
+        echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS WEBSOCKET\033[0m"
 		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
 		echo ""
 		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
@@ -1536,6 +1539,61 @@ exit 0' >$RCLOCAL
 				fun_bar 'fun_inisocks'
 				echo ""
 				echo -e "\033[1;32mSOCKS ATIVADO COM SUCESSO\033[1;33m"
+				sleep 3
+				fun_socks
+			fi
+        elif [[ "$resposta" = '2' ]]; then
+			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+				clear
+				echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
+				echo ""
+				fun_wssocksoff() {
+					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
+						screen -r -S "$pidproxy" -X quit
+					done
+					[[ $(grep -wc "wsproxy.py" /etc/autostart) != '0' ]] && {
+						sed -i '/wsproxy.py/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET\033[1;33m"
+				echo ""
+				fun_bar 'fun_wssocksoff'
+				echo ""
+				echo -e "\033[1;32mWEBSOCKET DESATIVADO COM SUCESSO!\033[1;33m"
+				sleep 3
+				fun_socks
+			else
+				clear
+				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+				read porta
+				[[ -z "$porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					sleep 3
+					clear
+					fun_conexao
+				}
+				verif_ptrs $porta
+				fun_iniwssocks() {
+					sleep 1
+					screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta
+					[[ $(grep -wc "wsproxy.py" /etc/autostart) = '0' ]] && {
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta; }" >>/etc/autostart
+					} || {
+						sed -i '/wsproxy.py/d' /etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta; }" >>/etc/autostart
+					}
+				}
+				echo ""
+				echo -e "\033[1;32mINICIANDO O WEBSOCKET\033[1;33m"
+				echo ""
+				fun_bar 'fun_iniwssocks'
+				echo ""
+				echo -e "\033[1;32WSSOCKS ATIVADO COM SUCESSO\033[1;33m"
 				sleep 3
 				fun_socks
 			fi
@@ -1730,7 +1788,116 @@ exit 0' >$RCLOCAL
 				echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;33mATIVE O SOCKS SSH PRIMEIRO !\033[1;33m"
 				sleep 2
 				fun_socks
-		  fi
+			fi
+        		elif [[ "$resposta" = '6' ]]; then
+			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+				clear
+				msgsocks=$(cat /etc/SSHPlus/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
+				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
+				echo ""
+				echo -e "\033[1;33mSTATUS: \033[1;32m$msgsocks"
+				echo""
+				echo -ne "\033[1;32mINFORME SEU STATUS\033[1;31m:\033[1;37m "
+				read msgg
+				[[ -z "$msgg" ]] && {
+					echo -e "\n\033[1;31mStatus invalido!"
+					sleep 2
+					fun_conexao
+				}
+				[[ ${msgg} != ?(+|-)+([a-zA-Z0-9-. ]) ]] && {
+					echo -e "\n\033[1;31m[\033[1;33m!\033[1;31m]\033[1;33m EVITE CARACTERES ESPECIAIS\033[0m"
+					sleep 2
+					fun_socks
+				}
+				echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m AZUL"
+				echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m VERDE"
+				echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m VERMELHO"
+				echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m AMARELO"
+				echo -e "\033[1;31m[\033[1;36m05\033[1;31m]\033[1;33m ROSA"
+				echo -e "\033[1;31m[\033[1;36m06\033[1;31m]\033[1;33m CYANO"
+				echo -e "\033[1;31m[\033[1;36m07\033[1;31m]\033[1;33m LARANJA"
+				echo -e "\033[1;31m[\033[1;36m08\033[1;31m]\033[1;33m ROXO"
+				echo -e "\033[1;31m[\033[1;36m09\033[1;31m]\033[1;33m PRETO"
+				echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m SEM COR"
+				echo ""
+				echo -ne "\033[1;32mQUAL A COR\033[1;31m ?\033[1;37m : "
+				read sts_cor
+				if [[ "$sts_cor" = "1" ]] || [[ "$sts_cor" = "01" ]]; then
+					cor_sts='blue'
+				elif [[ "$sts_cor" = "2" ]] || [[ "$sts_cor" = "02" ]]; then
+					cor_sts='green'
+				elif [[ "$sts_cor" = "3" ]] || [[ "$sts_cor" = "03" ]]; then
+					cor_sts='red'
+				elif [[ "$sts_cor" = "4" ]] || [[ "$sts_cor" = "04" ]]; then
+					cor_sts='yellow'
+				elif [[ "$sts_cor" = "5" ]] || [[ "$sts_cor" = "05" ]]; then
+					cor_sts='#F535AA'
+				elif [[ "$sts_cor" = "6" ]] || [[ "$sts_cor" = "06" ]]; then
+					cor_sts='cyan'
+				elif [[ "$sts_cor" = "7" ]] || [[ "$sts_cor" = "07" ]]; then
+					cor_sts='#FF7F00'
+				elif [[ "$sts_cor" = "8" ]] || [[ "$sts_cor" = "08" ]]; then
+					cor_sts='#9932CD'
+				elif [[ "$sts_cor" = "9" ]] || [[ "$sts_cor" = "09" ]]; then
+					cor_sts='black'
+				elif [[ "$sts_cor" = "10" ]]; then
+					cor_sts='null'
+				else
+					echo -e "\n\033[1;33mOPCAO INVALIDA !"
+					cor_sts='null'
+				fi
+				fun_msgsocks() {
+					msgsocks2=$(cat /etc/SSHPlus/wsproxy.py | grep "MSG =" | awk -F = '{print $2}')
+					sed -i "s/$msgsocks2/ '$msgg'/g" /etc/SSHPlus/wsproxy.py
+					sleep 1
+					cor_old=$(grep 'color=' /etc/SSHPlus/wsproxy.py | cut -d '"' -f2)
+					sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/SSHPlus/wsproxy.py
+				}
+				echo ""
+				echo -e "\033[1;32mALTERANDO STATUS!"
+				echo ""
+				fun_bar 'fun_msgsocks'
+                restartwssocks() {
+                    if ps x | grep wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+						echo -e "$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_wssks
+						for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
+							screen -r -S "$pidproxy" -X quit
+						done
+						screen -wipe >/dev/null
+						_Ptwssks="$(cat /tmp/Pt_wssks)"
+						sleep 1
+						screen -dmS ws python /etc/SSHPlus/wsproxy.py $_Ptwssks
+						rm /tmp/Pt_wssks
+					fi
+				}
+				echo ""
+				echo -e "\033[1;32mREINICIANDO WEBSOCKET!"
+				echo ""
+				fun_bar 'restartwssocks'
+				echo ""
+				echo -e "\033[1;32mSTATUS ALTERADO COM SUCESSO!"
+				sleep 2
+				fun_socks
+			else
+				clear
+				echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;33mATIVE O WEBSOCKET PRIMEIRO !\033[1;33m"
+				sleep 2
+				fun_socks
+			fi
+		elif [[ "$resposta" = '0' ]]; then
+			echo ""
+			echo -e "\033[1;31mRetornando...\033[0m"
+			sleep 1
+			fun_conexao
+		else
+			echo ""
+			echo -e "\033[1;31mOpcao invalida !\033[0m"
+			sleep 1
+			fun_socks
+		fi
+
+	}
+
 	fun_openssh() {
 		clear
 		echo -e "\E[44;1;37m            OPENSSH             \E[0m\n"
@@ -1878,14 +2045,9 @@ exit 0' >$RCLOCAL
 			} || {
 				sts5="\033[1;31m○ "
 			}
+
 			[[ "$(netstat -tlpn | grep 'python' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mSERVICO: \033[1;33mPROXY SOCKS \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
-				sts4="\033[1;32m◉ "
-			} || {
-				sts4="\033[1;31m○ "
-			}
-					[[ "$(netstat -tlpn | grep 'python' | wc -l)" != '0' ]] && {
-				echo -e "\033[1;32mSERVICO: \033[1;33mWEBSOCKET \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts4="\033[1;32m◉ "
 			} || {
 				sts4="\033[1;31m○ "
@@ -1920,12 +2082,11 @@ exit 0' >$RCLOCAL
 [\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mDROPBEAR $sts2\033[1;31m
 [\033[1;36m04\033[1;31m] \033[1;37m• \033[1;33mOPENVPN $sts5\033[1;31m
 [\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mPROXY SOCKS $sts4\033[1;31m
-[\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET $sts4\033[1;31m
-[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m
-[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mSSLH MULTIPLEX $sts7\033[1;31m
-[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mCHISEL $sts8\033[1;31m
-[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mV2RAY $xv2ray\033[1;31m
-[\033[1;36m11\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
+[\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m
+[\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH MULTIPLEX $sts7\033[1;31m
+[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHISEL $sts8\033[1;31m
+[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mV2RAY $xv2ray\033[1;31m
+[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
 [\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 			echo ""
 			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
@@ -1952,22 +2113,19 @@ exit 0' >$RCLOCAL
 				fun_socks
 				;;
 			6 | 06)
-				web_socks
-				;;
-			7 | 07)
 				inst_ssl
 				;;
-			8 | 08)
+			7 | 07)
 				fun_sslh
 				;;
-		    9 | 09)
+		    8 | 08)
 				fun_chisel
                 ;;              
-		    10 | 10)
+		    9 | 09)
 				v2raymanager
 				exit;
 				;;                
-			11 | 10)
+			10 | 10)
 				menu
 				;;
 			0 | 00)
@@ -1984,3 +2142,4 @@ exit 0' >$RCLOCAL
 		done
 	}
 	fun_conexao
+}
